[package]
name = "norikv-testkit"
version = "0.1.0"
edition = "2021"
publish = false
description = "Chaos simulator and linearizability checker."
repository = "https://github.com/your-org/norikv"
readme = "README.md"

[dependencies]
nori-observe = { path = "../nori-observe" }
