[package]
name = "nori-observe"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Vendor-neutral observability ABI for NoriKV and friends (metrics + typed events)."
repository = "https://github.com/your-org/norikv"
readme = "README.md"

[features]
obs = []

[dependencies]
