[package]
name = "norikv-transport-grpc"
version = "0.1.0"
edition = "2021"
publish = false
description = "gRPC transport + HTTP façade."
repository = "https://github.com/your-org/norikv"
readme = "README.md"

[dependencies]
nori-observe = { path = "../nori-observe" }
