[package]
name = "norikv-placement"
version = "0.1.0"
edition = "2021"
publish = false
description = "Shard planning + minimal-move diff."
repository = "https://github.com/your-org/norikv"
readme = "README.md"

[dependencies]
nori-observe = { path = "../nori-observe" }
